# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: RefineCraftAntiBuild
main: net.refination.refinecraft.antibuild.RefineCraftAntiBuild
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${project.version}-b${BUILD_NUMBER}
website: http://tiny.cc/RefineCraftCommands
description: Provides build protection.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, Iaccidentally]
depend: [RefineCraft]
